### ISSUE TITLE
centos 7 scl devtoolset-6 repo is broken

### ISSUE THREAD

**Issue by ghost** [sclorg-distgit/devtoolset-6#1]
Hi,

so when trying to install devtoolset-6 for centos 7 it fails with missing dependancies... I do have scl enabled. 

Any ideas ?

**Comment by remicollet** [comment]
For now, the SCL is not yet available in "stable" repository (only the metapackage was pushed there by mistake). 

Should be available soon.

Else, try using `--enablerepo=centos-sclo-rh-testing`

**Comment by aldanor** [comment]
Hi, wondering if there are any updates on this?

**Comment by ghost** [comment]
works now.
